// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGMQvzci1Rk5FOyU-_zPsB5zqyvSw6RM',
    appId: '1:977671322128:web:20e01aa56663d321d0a895',
    messagingSenderId: '977671322128',
    projectId: 'mysecondfirebase-79c6e',
    authDomain: 'mysecondfirebase-79c6e.firebaseapp.com',
    storageBucket: 'mysecondfirebase-79c6e.appspot.com',
    measurementId: 'G-KQTE6JJNEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBf8oIyscrtVZI-HlQA0ftcjF5hSmEOQ',
    appId: '1:977671322128:android:2b7147ccc7a195ffd0a895',
    messagingSenderId: '977671322128',
    projectId: 'mysecondfirebase-79c6e',
    storageBucket: 'mysecondfirebase-79c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKr8IU5aL5oL6U-opT9UWsQO8GgLghZM',
    appId: '1:977671322128:ios:304c5fb2cabbabb7d0a895',
    messagingSenderId: '977671322128',
    projectId: 'mysecondfirebase-79c6e',
    storageBucket: 'mysecondfirebase-79c6e.appspot.com',
    iosBundleId: 'com.karon.chatapp',
  );
}
