// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5m3elNBZ_mVpY78FfDkIQboWxWID50Y',
    appId: '1:653878508352:web:bbf0da7ffbcaaf909658a5',
    messagingSenderId: '653878508352',
    projectId: 'myfirstfirebase-4116f',
    authDomain: 'myfirstfirebase-4116f.firebaseapp.com',
    storageBucket: 'myfirstfirebase-4116f.appspot.com',
    measurementId: 'G-CXLL31J4PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjmXlpkt0dZmtuj_yZtH5KgMPJd2D5tas',
    appId: '1:653878508352:android:90b0cc89256cb68c9658a5',
    messagingSenderId: '653878508352',
    projectId: 'myfirstfirebase-4116f',
    storageBucket: 'myfirstfirebase-4116f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4CZaF73yNGlkzRycYqhxDJKE8LEGVn4',
    appId: '1:653878508352:ios:ef4caea91832b61b9658a5',
    messagingSenderId: '653878508352',
    projectId: 'myfirstfirebase-4116f',
    storageBucket: 'myfirstfirebase-4116f.appspot.com',
    iosBundleId: 'com.karon.firebaseexample',
  );
}
