// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkcYsRVQ8yJcDHlxd0jTMAW5ahVoLSfM',
    appId: '1:161720937695:web:45356215bd2e3b5e2a0d6a',
    messagingSenderId: '161720937695',
    projectId: 'mythirdproject-2a362',
    authDomain: 'mythirdproject-2a362.firebaseapp.com',
    storageBucket: 'mythirdproject-2a362.appspot.com',
    measurementId: 'G-B3DEV8SQ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyzwIRt2JQT6c0V1jYHjeM-CupUQwPBU',
    appId: '1:161720937695:android:d4da66e0e8073a3c2a0d6a',
    messagingSenderId: '161720937695',
    projectId: 'mythirdproject-2a362',
    storageBucket: 'mythirdproject-2a362.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYD5c7QUdwInKmNGLlbJGnoKngmy_cno',
    appId: '1:161720937695:ios:66d201fe75cb2ba92a0d6a',
    messagingSenderId: '161720937695',
    projectId: 'mythirdproject-2a362',
    storageBucket: 'mythirdproject-2a362.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
